### ISSUE TITLE
Works with MicroScan3

### ISSUE THREAD

**Issue by NikolasE** [Tractonomy/sick_safetyscanners#2]
I tested the repository with a MicroScan3 and got data (range and intensity) immediately.

**Comment by eliasdc** [comment]
thanks for testing. Currently we are not ready to release it but we keep it in sync (as best we can) with the official ros repository.

**Comment by NikolasE** [comment]
Regarding the release: Why did you switch to Boost-looging and removed the ROS2-logging? This makes the node a bit harder to use in a ROS2 environment

**Comment by eliasdc** [comment]
All those packages don't rely on ROS2 and as boost was already used my colleague changed it to boost logging. I can revert it back to ROS2 logging if you think this makes more sense.
